apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: yashwanthjavvaji/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/users'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-expiration-time
                  key: JWT_EXPIRATION_TIME
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-access-token-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-access-token-expiration-time
                  key: JWT_ACCESS_TOKEN_EXPIRATION_TIME
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-token-secret
                  key: JWT_REFRESH_TOKEN_SECRET
            - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-token-expiration-time
                  key: JWT_REFRESH_TOKEN_EXPIRATION_TIME

---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
      