apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: yashwanthjavvaji/orders
          env:
            - name: MONGO_URI
              value: 'mongodb://orders-mongo-srv:27017/orders'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-expiration-time
                  key: JWT_EXPIRATION_TIME
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-access-token-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-access-token-expiration-time
                  key: JWT_ACCESS_TOKEN_EXPIRATION_TIME
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-token-secret
                  key: JWT_REFRESH_TOKEN_SECRET
            - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: jwt-refresh-token-expiration-time
                  key: JWT_REFRESH_TOKEN_EXPIRATION_TIME
                  
---

apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
      