
#ansible-playbook playbook_configuration_ec2.yml -i hosts 

---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: all
  remote_user: ec2-user
  tasks:
     - name: Transfer executable script script
       copy: src=./configuration_monitoring.sh dest=/home/ec2-user/ mode=0777      
 
     - name: Execute the script
       command: sh /home/ec2-user/configuration_monitoring.sh 
