
#ansible-playbook playbook_configuration_ec2.yml -i hosts 

---
- name: Let's copy our executable script to remote location, execute script and get result back.
  hosts: worker
  #remote_user: ubuntu
  remote_user: ec2-user

  tasks:
     - name: Transfer executable script script
       #copy: src=./configuration_script_worker.sh dest=/home/ubuntu/ mode=0777   
       copy: src=./configuration_script_worker.sh dest=/home/ec2-user mode=0777   
       
     - name: Execute the script
       #command: sh /home/ubuntu/configuration_script_worker.sh 
       
       command: sh /home/ec2-user/configuration_script_worker.sh 

