#create keypair in us-east-1
#create ~/.boto file
#https://www.youtube.com/watch?v=2_GXHygzWSQ&t=487s&ab_channel=TechArkit
#ansible-playbook
#Add all traffic to security group(temporary) --> todo


---
  - name: Provision an EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning
    vars:
      instance_type: t2.medium
      security_group: sg_majorproject
      image: ami-0e472ba40eb589f49                             
      #ami-0308a201dfce87071
      region: us-east-1
      keypair: majorproject
      count: 3
      volumes:
       - device_name: /dev/sda1
         volume_size: 30
         delete_on_termination: yes

    tasks:

      - name: Create New security group with below given name
        local_action:
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for Newly Created EC2 Instance
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 9090
              to_port: 9090
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 3000
              to_port: 3000
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
            


      - name: Launch the new t2 medium EC2 Instance
        local_action: ec2
                      group={{ security_group }}
                      instance_type={{ instance_type}}
                      image={{ image }}
                      wait=true
                      region={{ region }}
                      keypair={{ keypair }}
                      count={{count}}
                      volumes={{volumes}}
                      
        register: ec2

      - name: Wait for EC2 Instance to Spin-up and ready for SSH access
        local_action: wait_for
                      host={{ item.public_ip }}
                      port=22
                      state=started
        with_items: "{{ ec2.instances }}"

      - name: Adding Tags to Identify
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: Ec2 Server
            Owner: SaiKumar
            PurPose: Testing EC2 Instance From Ansible